export const questions = [
    { question: "Please provide your Name.", field: "name"},
    { question: "What is your Age?", field: "age"},
    { question: "What is your Gender?", field: "gender"},
    { question: "Do you have delayed speech and language development?", field: "delayedSpeech", type: "boolean" },
    { question: "Do you experience difficulty in social interactions?", field: "socialInteractionIssues", type: "boolean" },
    { question: "Do you have repetitive behaviors or routines?", field: "repetitiveBehaviors", type: "boolean" },
    { question: "Do you have sensitivity to sensory stimuli?", field: "sensitivity", type: "boolean" },
    { question: "Provide your birth history.", field: "birthHistory", customOptions:["Full-term, cesarean delivery",  "Full-term, normal vaginal delivery","Preterm, normal vaginal delivery"] },
    { question: "What was your birth weight (kg)?", field: "birthWeight" },
    { question: "Were there any complications during pregnancy or delivery?", field: "complications",type: "boolean" },
    { question: "At what age did you roll over (months)?", field: "rolledOver" },
    { question: "At what age did you sit without support (months)?", field: "satWithoutSupport" },
    { question: "At what age did you walk independently (months)?", field: "walkedIndependently" },
    { question: "At what age did you say your first words (months)?", field: "firstWords" },
    { question: "Have you observed limited vocabulary or echolalia?", field: "limitedVocabulary", type: "boolean" },
    { question: "Have you had frequent ear infections?", field: "earInfections", type: "boolean" },
    { question: "Have you experienced significant illnesses or hospitalizations?", field: "illnesses", type: "boolean"  },
    { question: "Is there a family history of autism or related disorders?", field: "familyHistory", type: "boolean" },
    { question: "Do you have other neurological or psychiatric disorders?", field: "neurologicalDisorders", type: "boolean"  },
    { question: "Do you live with parents?", field: "livingSituation", type: "boolean"},
    { question: "How many siblings you have?", field: "siblingsCount"},
    { question: "Do you attend a special education program?", field: "educationProgram",type: "boolean"},
    { question: "Do you have limited peer interactions and prefer solitary activities?", field: "peerInteractions", type: "boolean" },
    { question: "Do you avoid eye contact?", field: "eyeContact", type: "boolean" },
    { question: "Do you engage in hand-flapping when excited?", field: "handFlapping", type: "boolean" },
    // { question: "What is your cranial nerve function?", field: "cranialNerves", customOptions: ["Intact"] },
    // { question: "What is your motor function?", field: "motorFunction",customOptions: ["Normal tone and strength"]},
    // { question: "What is your sensory function?", field: "sensoryFunction",customOptions: ["Overreactive to tactile stimuli","Normal"] },
    { question: "How is your coordination?", field: "coordination",customOptions: ["Appropriate for age","Appropriate for age, some clumsiness noted"] },
    { question: "Do you have difficulty with back-and-forth conversation?", field: "conversationDifficulty", type: "boolean" },
    { question: "Do you have intense interest in specific topics?", field: "intenseInterests" ,type: "boolean"},
    { question: "Do you engage in repetitive movements or rituals?", field: "repetitiveMovements", type: "boolean" },
    { question: "Have you taken a hearing test?", field: "hearingTest" ,customOptions: ["Normal", "No"] },
    { question: "Have you undergone genetic testing?", field: "geneticTesting",customOptions: ["Negative for Fragile X Syndrome and other common genetic markers associated with ASD", "No"] },
    { question: "Have you done neuroimaging (MRI)?", field: "neuroImaging",customOptions: ["No structural abnormalities", "No"] },
];